/* run scraper */

const characterAttackType = {
  'Knight Emperor': 'Physical',
  'Rune Master': 'Magical',
  'Immortal': 'Physical',
  'Genesis': 'Magical',
  'Aether Sage': 'Magical',
  'Oz Sorcerer': 'Magical',
  'Metamorphy': 'Physical',
  'Lord Azoth': 'Physical',
  'Anemos': 'Physical',
  'Daybreaker': 'Magical',
  'Twilight': 'Physical',
  'Prophetess': 'Magical',
  'Furious Blade': 'Physical',
  'Rage Hearts': 'Magical',
  'Nova Imperator': 'Magical',
  'Revenant': 'Physical',
  'Code: Ultimate': 'Magical',
  'Code: Esencia': 'Physical',
  'Code: Sariel': 'Magical',
  'Code: Antithese': 'Physical',
  'Comet Crusader': 'Physical',
  'Fatal Phantom': 'Magical',
  'Centurion': 'Magical',
  'Dius Aer': 'Physical',
  'Apsara': 'Physical',
  'Devi': 'Magical',
  'Shakti': 'Physical',
  'Surya': 'Magical',
  'Empire Sword': 'Physical',
  'Flame Lord': 'Magical',
  'Bloody Queen': 'Physical',
  'Adrestia': 'Magical',
  'Doom Bringer': 'Magical',
  'Dominator': 'Physical',
  'Mad Paradox': 'Magical',
  'Overmind': 'Physical',
  'Catastrophe': 'Physical',
  'Innocent': 'Magical',
  'Diangelion': 'Physical',
  'Demersio': 'Magical',
  'Tempest Burster': 'Physical',
  'Black Massacre': 'Physical',
  'Minerva': 'Magical',
  'Prime Operator': 'Magical',
  'Richter': 'Physical',
  'Bluhen': 'Magical',
  'Herrscher': 'Magical',
  'Opferung': 'Physical',
  'Eternity Winner': 'Physical',
  'Radiant Soul': 'Magical',
  'Nisha Labyrinth': 'Physical',
  'Twins Picaro': 'Magical',
  'Liberator': 'Physical',
  'Celestia': 'Magical',
  'Nyx Pieta': 'Physical',
  'Morpheus': 'Magical',
  'Gembliss': 'Physical',
  'Avarice': 'Physical',
  'Achlys': 'Magical',
  'Mischief': 'Magical',
};
